import mxnet as mx
input_data = mx.nd.arange(-8,8).reshape((1,1,4,4))
print("Input data:")
print(input_data)
out_data_relu = mx.nd.Activation(data=input_data, act_type='relu')
print("Relu activation result:")
print(out_data_relu)

out_data_sigmoid = mx.nd.Activation(data=input_data, act_type='sigmoid')
print("Sigmoid activation result:")
print(out_data_sigmoid)
out_data_softrelu = mx.nd.Activation(data=input_data, act_type='softrelu')
print("Softrelu activation result:")
print(out_data_softrelu)
out_data_softsign = mx.nd.Activation(data=input_data, act_type='softsign')
print("Softsign activation result:")
print(out_data_softsign)
out_data_tanh = mx.nd.Activation(data=input_data, act_type='tanh')
print("Tanh activation result:")
print(out_data_tanh)